#!/bin/bash

#Producto: Utilidades del sistema
#PUNTO 2
#Esta función tiene por objeto disparar procesos. Es complementaria a Stop
#Puede ser invocada desde la línea de comando o bien desde otro comando.
#No se puede arrancar un proceso si éste ya se encuentra corriendo. No se puede arrancar un proceso si la inicialización de ambiente no fue realizada. 
#Si esta función es invocada por un comando, actualizar el log indicando el resultado de la operación
#Explicar su uso en el README.

#Ejecuta con & para independizar el proceso de la terminal
./Daemon &


