#!/bin/bash

#Punto 1. Ambiente– sprint 1
#Ningún comando puede ser ejecutado sin la inicialización del ambiente 
#Para determinar el directorio de novedades, aceptados, rechazados, etc. se deben leer las variables de ambiente.


############Inicializacion la utilizo para probar, cuando se integre quitar################
GRUPO="/home/uje/sisop/sisop_grupo3/test_daemon"
BINARIOS=$GRUPO"/BIN"
MAESTROS=$GRUPO"/MAE"
NOVEDADES=$GRUPO"/nov"
ACEPTADOS=$GRUPO"/OK"
RECHAZADOS=$GRUPO"/NOK"
VALIDADOS=$GRUPO"/PROC"
REPORTES=$GRUPO"/INFO"
LOG=$GRUPO"/LOG"
############################################################################################

#REVISAR QUE LAS VARIABLES DE AMBIENTE SEAN LAS MISMAS QUE LAS SETEADAS EN EL INICIALIZADOR
VARIABLES_AMBIENTE=($GRUPO $BINARIOS $MAESTROS $NOVEDADES $ACEPTADOS $RECHAZADOS $VALIDADOS $REPORTES $LOG)
COUNT_VARIABLES_AMBIENTE=9

#Valida que el ambiente haya sido inicializado previamente
#Recibe el array de variables de ambiente y el contador de variables
#Si alguna variable esta vacia, el size del array es menor al contador
function validar_ambiente_inicializado() {
	if [ ${#VARIABLES_AMBIENTE[@]} -ne $2 ] 
		then
		echo "LOG: AMBIENTE NO INICIALIZADO"
		exit 1 #corta la ejecucion del programa
	fi
}


validar_ambiente_inicializado $VARIABLES_AMBIENTE $COUNT_VARIABLES_AMBIENTE

#Ejecuta con & para independizar el proceso de la terminal
sh daemon &

echo "Daemon iniciado con process id: $!"

